# -*- coding: utf-8 -*-
"""
/***************************************************************************
 Semenova
                                 A QGIS plugin
 This plugin finds water (natural=water)
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2025-04-12
        git sha              : $Format:%H$
        copyright            : (C) 2025 by Semenova Salomia
        email                : .
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""
from qgis.PyQt.QtCore import QSettings, QTranslator, QCoreApplication
from qgis.PyQt.QtGui import QIcon
from qgis.PyQt.QtWidgets import QAction
from qgis.core import QgsVectorLayer, QgsFeature, QgsProject, QgsFillSymbol

# Initialize Qt resources from file resources.py
from .resources import *
# Import the code for the dialog
from .semenova_dialog import SemenovaDialog
import os.path


class Semenova:
    """QGIS Plugin Implementation."""

    def __init__(self, iface):
        """Constructor."""
        self.iface = iface
        self.plugin_dir = os.path.dirname(__file__)
        locale = QSettings().value('locale/userLocale')[0:2]
        locale_path = os.path.join(
            self.plugin_dir,
            'i18n',
            'Semenova_{}.qm'.format(locale))

        if os.path.exists(locale_path):
            self.translator = QTranslator()
            self.translator.load(locale_path)
            QCoreApplication.installTranslator(self.translator)

        self.actions = []
        self.menu = self.tr(u'&Semenova')
        self.first_start = None

    def tr(self, message):
        return QCoreApplication.translate('Semenova', message)

    def add_action(self, icon_path, text, callback, enabled_flag=True,
                  add_to_menu=True, add_to_toolbar=True, status_tip=None,
                  whats_this=None, parent=None):
        icon = QIcon(icon_path)
        action = QAction(icon, text, parent)
        action.triggered.connect(callback)
        action.setEnabled(enabled_flag)

        if status_tip:
            action.setStatusTip(status_tip)
        if whats_this:
            action.setWhatsThis(whats_this)

        if add_to_toolbar:
            self.iface.addToolBarIcon(action)
        if add_to_menu:
            self.iface.addPluginToMenu(self.menu, action)

        self.actions.append(action)
        return action

    def initGui(self):
        icon_path = ':/plugins/semenova/icon.png'
        self.add_action(
            icon_path,
            text=self.tr(u'Semenova'),
            callback=self.run,
            parent=self.iface.mainWindow())
        self.first_start = True

    def unload(self):
        for action in self.actions:
            self.iface.removePluginMenu(self.tr(u'&Semenova'), action)
            self.iface.removeToolBarIcon(action)

    def run(self):
        """Основной метод выполнения"""
        natural_layer = self.iface.activeLayer()

        if not natural_layer:
            self.iface.messageBar().pushCritical("Ошибка", "Нет активного слоя! Выберите векторный слой с OSM данными.")
            return

        if not isinstance(natural_layer, QgsVectorLayer):
            self.iface.messageBar().pushCritical("Ошибка", "Слой не векторный! Используйте векторные OSM данные.")
            return

        # Фильтрация объектов natural=water
        features = []
        valid_natural_values = ["water"]

        for feature in natural_layer.getFeatures():
            if "natural" in feature.fields().names():
                natural_value = feature["natural"]
                if natural_value in valid_natural_values:  # Исправлено natral_value -> natural_value
                    features.append(feature)

        if not features:
            self.iface.messageBar().pushWarning("Внимание", "Не найдено водных объектов с тегом natural=water")
            return

        # Диагностика
        invalid_geoms = sum(1 for f in features if not f.geometry().isGeosValid())
        print(f"Найдено объектов: {len(features)}")
        print(f"Некорректных геометрий: {invalid_geoms}")
        print(f"CRS слоя: {natural_layer.crs().authid()}")

        # Создаем результирующий слой
        result_layer = QgsVectorLayer(
            f"Polygon?crs={natural_layer.crs().authid()}",
            "вода (natural=water)",
            "memory"
        )

        # Настройка слоя
        result_layer.startEditing()
        result_layer.dataProvider().addAttributes(natural_layer.fields())
        result_layer.updateFields()

        # Копируем объекты с проверкой геометрии
        valid_features = []
        for feature in features:
            new_feature = QgsFeature()
            geom = feature.geometry()

            if not geom.isGeosValid():
                geom = geom.makeValid()

            new_feature.setGeometry(geom)
            new_feature.setAttributes(feature.attributes())
            valid_features.append(new_feature)

        result_layer.dataProvider().addFeatures(valid_features)
        result_layer.commitChanges()
        result_layer.updateExtents()

        # Применяем стиль
        symbol = QgsFillSymbol.createSimple({
            'color': '0,0,255,150',  # Синий с прозрачностью (более подходит для воды)
            'color_border': '0,0,150',  # Темно-синяя граница
            'width_border': '0.5'
        })
        result_layer.renderer().setSymbol(symbol)
        result_layer.triggerRepaint()

        # Добавляем слой на карту
        QgsProject.instance().addMapLayer(result_layer)

        # Центрируем карту
        canvas = self.iface.mapCanvas()
        canvas.setExtent(result_layer.extent())
        canvas.refresh()

        # Финализация
        print("Слой успешно создан и добавлен на карту")
        self.iface.messageBar().pushSuccess("Готово", f"Найдено водных объектов: {len(features)}")